clamping map zoom out and long and lat ranges to USA
HF-RapidResponse/Basic-Income-Map pull request #4
Opened 2021-06-06 01:23 UTC by ecaoile

![Uploading image.png…]()

Fix inspired by [this](https://github.com/visgl/react-map-gl/issues/442)

2021-06-08 07:07 UTC, sphilazar requested changes
Very minor change requested - functionally this looks great, thanks for kicking off our development!

2021-06-08 07:07 UTC, sphilazar commented on src/components/Map.jsx
> +              if (viewport.longitude < minLongitude || viewport.longitude > 60) {
Would prefer if we store the 60 as a descriptive `const` with maybe a comment as to why this number is selected / how to verify functionality (e.g. center of eastern-most limit of map is 60th longitude etc). As someone reviewing the code I'm confused why we compare with `minLongitude` but logic is not parallelized by also comparing with `maxLongitude`, so would be nice to clarify

2021-06-08 07:16 UTC, ecaoile commented on src/components/Map.jsx
> +              if (viewport.longitude < minLongitude || viewport.longitude > 60) {
I wasn't sure what to call the 60 degrees since it's not exactly the other side of the world from the US. The reason I added that number is the weird edge case of zooming out and then trying to go all the way left or right. The regular min and max longitude don't work because the world is round, and you're looping around to high values if you go all the way left while zoomed out.

2021-06-08 07:33 UTC, ecaoile commented on src/components/Map.jsx
> +              if (viewport.longitude < minLongitude || viewport.longitude > 60) {
It seems that no matter what number you put that "border", there's no way to avoid clipping to the other side 100% of the time. It's kinda weird, but not exactly breaking. I was just taking QA to the extreme

2021-06-08 07:44 UTC, ecaoile commented on src/components/Map.jsx
> +              if (viewport.longitude < minLongitude || viewport.longitude > 60) {
created variable with explanation

2021-06-09 00:39 UTC, sphilazar approved these changes
Thanks for the update, this looks great!

2021-06-09 00:39 UTC, merged